/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BinaryCodedDecimalDetail, DecimalDetail, TimeEmitterDetail } from "./components/time-emitter/types";
export namespace Components {
    interface TimeDisplay {
    }
    interface TimeDisplayBinary {
        "timeKey": keyof BinaryCodedDecimalDetail;
        "timeValue": string[];
    }
    interface TimeDisplayDecimal {
        "timeKey": keyof DecimalDetail;
        "timeValue": string;
    }
    interface TimeEmitter {
        "updateInterval": number;
    }
}
declare global {
    interface HTMLTimeDisplayElement extends Components.TimeDisplay, HTMLStencilElement {
    }
    var HTMLTimeDisplayElement: {
        prototype: HTMLTimeDisplayElement;
        new (): HTMLTimeDisplayElement;
    };
    interface HTMLTimeDisplayBinaryElement extends Components.TimeDisplayBinary, HTMLStencilElement {
    }
    var HTMLTimeDisplayBinaryElement: {
        prototype: HTMLTimeDisplayBinaryElement;
        new (): HTMLTimeDisplayBinaryElement;
    };
    interface HTMLTimeDisplayDecimalElement extends Components.TimeDisplayDecimal, HTMLStencilElement {
    }
    var HTMLTimeDisplayDecimalElement: {
        prototype: HTMLTimeDisplayDecimalElement;
        new (): HTMLTimeDisplayDecimalElement;
    };
    interface HTMLTimeEmitterElement extends Components.TimeEmitter, HTMLStencilElement {
    }
    var HTMLTimeEmitterElement: {
        prototype: HTMLTimeEmitterElement;
        new (): HTMLTimeEmitterElement;
    };
    interface HTMLElementTagNameMap {
        "time-display": HTMLTimeDisplayElement;
        "time-display-binary": HTMLTimeDisplayBinaryElement;
        "time-display-decimal": HTMLTimeDisplayDecimalElement;
        "time-emitter": HTMLTimeEmitterElement;
    }
}
declare namespace LocalJSX {
    interface TimeDisplay {
    }
    interface TimeDisplayBinary {
        "timeKey"?: keyof BinaryCodedDecimalDetail;
        "timeValue"?: string[];
    }
    interface TimeDisplayDecimal {
        "timeKey"?: keyof DecimalDetail;
        "timeValue"?: string;
    }
    interface TimeEmitter {
        "onTimeEmitterUpdate"?: (event: CustomEvent<TimeEmitterDetail>) => void;
        "updateInterval"?: number;
    }
    interface IntrinsicElements {
        "time-display": TimeDisplay;
        "time-display-binary": TimeDisplayBinary;
        "time-display-decimal": TimeDisplayDecimal;
        "time-emitter": TimeEmitter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "time-display": LocalJSX.TimeDisplay & JSXBase.HTMLAttributes<HTMLTimeDisplayElement>;
            "time-display-binary": LocalJSX.TimeDisplayBinary & JSXBase.HTMLAttributes<HTMLTimeDisplayBinaryElement>;
            "time-display-decimal": LocalJSX.TimeDisplayDecimal & JSXBase.HTMLAttributes<HTMLTimeDisplayDecimalElement>;
            "time-emitter": LocalJSX.TimeEmitter & JSXBase.HTMLAttributes<HTMLTimeEmitterElement>;
        }
    }
}
